#!/bin/sh
# Install on the ImmortalWrt router: run this from the deploy directory, after the binary is in place. Idempotent.
set -e

BIN=/usr/bin/ds-lite-punch
INIT=/etc/init.d/ds-lite-punch
ENV=/etc/ds-lite-punch.env
MAN=/usr/share/man/man8/ds-lite-punch.8

[ -x "$BIN" ] || { echo "error: $BIN not present (scp the binary first)"; exit 1; }

cp ds-lite-punch.init "$INIT"
chmod 755 "$INIT"
if [ ! -f "$ENV" ]; then
    cp ds-lite-punch.env "$ENV"
    echo "installed default $ENV — edit BIND/TARGET for your console"
fi

# The manual page, generated by tools/argdoc, and shipped in every release beside the binary.
if [ -f man/ds-lite-punch.8 ]; then
    mkdir -p /usr/share/man/man8
    cp man/ds-lite-punch.8 "$MAN"
    chmod 644 "$MAN"
    echo "installed $MAN (read it with: man ds-lite-punch)"
fi

# The allowlist, created empty: no device's mapping is kept alive until an operator names one.
ALLOWLIST=/etc/ds-lite-punch.allow
if [ ! -f "$ALLOWLIST" ]; then
    printf '# Devices whose flows get the hold (call/0025). One IPv4 address per\n# line; the entry grants maintenance and never authority.\n' > "$ALLOWLIST"
    chmod 644 "$ALLOWLIST"
    echo "installed empty $ALLOWLIST"
fi

"$INIT" enable
"$INIT" restart
sleep 3
echo "== service status =="
"$INIT" enabled && echo "enabled"
pgrep -fl ds-lite-punch || echo "NOT RUNNING"
echo "== tuple =="
cat /run/ds-lite-punch/tuple 2>/dev/null || echo "no tuple yet"

cat <<'EOF'
== what to do next ==
1. Name the devices that get the hold in /etc/ds-lite-punch.allow, one IPv4
   address per line.  The file is installed empty, so no device is held until
   you name one, and a held flow costs about half a packet a second.
2. Seed the first DeviceProtection identity in /etc/ds-lite-punch.acl, then
   restart the service.  Until the store has an identity, every role-gated
   action answers 606.
3. Read the mapping the carrier is holding: cat /run/ds-lite-punch/tuple
4. Read the daemon's events: logread | grep ds-lite-punch
5. Read the manual page: man ds-lite-punch
EOF
